project:
  type: website
  output-dir: docs

website:
  title: "Holly Hall"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: posts.qmd
        text: Notes
      - href: projects.qmd
        text: Projects
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    

editor: visual

